#!/bin/bash

matched=($(grep -r "[0-9a-zA-Z]\{${1}\}" . -o))
cd `dirname $0`
for r in "${matched[@]}"
do
  result=`python ./randomness.py ${r##*:}`
  if [ "$result" != "" ]; then
    echo ${r%%:*} $result
  fi
done
